/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Guerreiro;
import servicos.GuerreiroServicos;
import servicos.ServicosFactory;

/**
 *
 * @author 182310086
 */
public class JFGuerreiro extends javax.swing.JFrame {
    int idEdit;

    /**
     * Creates new form JFGuerreiro
     */
    public JFGuerreiro() {
        initComponents();
        addRowToTable();
        jbDeletarGuerreiro.setVisible(false);
        jbEditarGuerreiro.setVisible(false);
    }

    public void addRowToTable(){
        //pega a modelagem da tabela na inteface grafica
        DefaultTableModel model = (DefaultTableModel) jtGuerreiro.getModel();
        model.getDataVector().removeAllElements();//remove linhas
        model.fireTableDataChanged();
        Object rowData[] = new Object[6];//vetor da tabela
        GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
        //ler dados e add no vetor e tabela
        for (Guerreiro guerreiro : guerreiroS.listaGuerreiros()) {
            rowData[0] = guerreiro.getId();
            rowData[1] = guerreiro.getNome();
            rowData[2] = guerreiro.getPele();         
            rowData[3] = guerreiro.isSexo() == false ? "FEMININO" : "MASCULINO";//if ternary
            rowData[4] = guerreiro.getArmamento();
            rowData[5] = guerreiro.getPontoDeVida();
            model.addRow(rowData);
        }
    }//fim add to table
    
    private void limpaCampos() {
        jtfNomeGuerreiro.setText("");
        jtfOlhoGuerreiro.setText("");
        jtfCabeloGuerreiro.setText("");
        jtfPeleGuerreiro.setText("");
        bgSexoGuerreiro.clearSelection();
        jtfNomeGuerreiro.requestFocus();
        jtfArmaGuerreiro.setText("");
    }//limpa campos
    
    private boolean validaInputs() {
        if (jtfNomeGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o nome");
            jtfNomeGuerreiro.requestFocus();
            return false;
        }
        if (jtfCabeloGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o cabelo");
            jtfCabeloGuerreiro.requestFocus();
            return false;
        }
        if (jtfOlhoGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o olho");
            jtfOlhoGuerreiro.requestFocus();
            return false;
        }
        if (jtfPeleGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher a pele");
            jtfPeleGuerreiro.requestFocus();
            return false;
        }
        if(jtfArmaGuerreiro.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencher a arma");
            jtfArmaGuerreiro.requestFocus();
            return false;
        }
        if (!jrbFemininoGuerreiro.isSelected() && !jrbMasculinoGuerreiro.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecionar sexo!");
            return false;
        }//o sinal de ! está negando o retorno do select
        return true;
    }//validando dados
    
    private void jbDefault() {
        jbSalvarGuerreiro.setText("Salvar");
        jLSexoGuerreiro.setVisible(true);
        jrbFemininoGuerreiro.setVisible(true);
        jrbMasculinoGuerreiro.setVisible(true);
        jbLimparGuerreiro.setEnabled(true);
        jbDeletarGuerreiro.setText("Deletar");
        jbDeletarGuerreiro.setVisible(false);
        jbEditarGuerreiro.setVisible(false);
    }//botoes zerados
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexoGuerreiro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeGuerreiro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfCabeloGuerreiro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfPeleGuerreiro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfOlhoGuerreiro = new javax.swing.JTextField();
        jLSexoGuerreiro = new javax.swing.JLabel();
        jrbFemininoGuerreiro = new javax.swing.JRadioButton();
        jrbMasculinoGuerreiro = new javax.swing.JRadioButton();
        jbSalvarGuerreiro = new javax.swing.JButton();
        jbLimparGuerreiro = new javax.swing.JButton();
        jbEditarGuerreiro = new javax.swing.JButton();
        jbDeletarGuerreiro = new javax.swing.JButton();
        jScrollPaneG = new javax.swing.JScrollPane();
        jtGuerreiro = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jtfArmaGuerreiro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Guerreiro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nome: ");

        jtfNomeGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeGuerreiroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cabelo: ");

        jtfCabeloGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCabeloGuerreiroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Pele:");

        jtfPeleGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPeleGuerreiroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Olho:");

        jtfOlhoGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOlhoGuerreiroActionPerformed(evt);
            }
        });

        jLSexoGuerreiro.setText("Sexo:");

        bgSexoGuerreiro.add(jrbFemininoGuerreiro);
        jrbFemininoGuerreiro.setText("Feminino");
        jrbFemininoGuerreiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFemininoGuerreiroMouseClicked(evt);
            }
        });
        jrbFemininoGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFemininoGuerreiroActionPerformed(evt);
            }
        });

        bgSexoGuerreiro.add(jrbMasculinoGuerreiro);
        jrbMasculinoGuerreiro.setText("Masculino");
        jrbMasculinoGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMasculinoGuerreiroActionPerformed(evt);
            }
        });

        jbSalvarGuerreiro.setText("Salvar");
        jbSalvarGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarGuerreiroActionPerformed(evt);
            }
        });

        jbLimparGuerreiro.setText("Limpar");
        jbLimparGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparGuerreiroActionPerformed(evt);
            }
        });

        jbEditarGuerreiro.setText("Editar");
        jbEditarGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarGuerreiroActionPerformed(evt);
            }
        });

        jbDeletarGuerreiro.setText("Deletar");
        jbDeletarGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarGuerreiroActionPerformed(evt);
            }
        });

        jtGuerreiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Pele", "Sexo", "Arma", "HP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtGuerreiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtGuerreiroMouseClicked(evt);
            }
        });
        jScrollPaneG.setViewportView(jtGuerreiro);
        if (jtGuerreiro.getColumnModel().getColumnCount() > 0) {
            jtGuerreiro.getColumnModel().getColumn(0).setResizable(false);
            jtGuerreiro.getColumnModel().getColumn(1).setResizable(false);
            jtGuerreiro.getColumnModel().getColumn(2).setResizable(false);
            jtGuerreiro.getColumnModel().getColumn(3).setResizable(false);
            jtGuerreiro.getColumnModel().getColumn(4).setResizable(false);
            jtGuerreiro.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Arma: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jScrollPaneG, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNomeGuerreiro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPeleGuerreiro)
                            .addComponent(jtfCabeloGuerreiro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLSexoGuerreiro)
                                .addGap(18, 18, 18)
                                .addComponent(jrbMasculinoGuerreiro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbFemininoGuerreiro)
                                    .addComponent(jtfOlhoGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSalvarGuerreiro)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimparGuerreiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jbEditarGuerreiro)
                        .addGap(18, 18, 18)
                        .addComponent(jbDeletarGuerreiro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfArmaGuerreiro)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNomeGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCabeloGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfOlhoGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfPeleGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSexoGuerreiro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbFemininoGuerreiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbMasculinoGuerreiro)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfArmaGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarGuerreiro)
                    .addComponent(jbLimparGuerreiro)
                    .addComponent(jbEditarGuerreiro)
                    .addComponent(jbDeletarGuerreiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneG, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimparGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparGuerreiroActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jbLimparGuerreiroActionPerformed

    private void jbSalvarGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarGuerreiroActionPerformed
       if (jbSalvarGuerreiro.getText().equals("Salvar")) {
            if (validaInputs()) {
                Guerreiro g = new Guerreiro();
                g.setNome(jtfNomeGuerreiro.getText().toUpperCase());
                g.setCabelo(jtfCabeloGuerreiro.getText().toUpperCase());
                g.setOlho(jtfOlhoGuerreiro.getText().toUpperCase());
                g.setCabelo(jtfCabeloGuerreiro.getText().toUpperCase());
                g.setPele(jtfPeleGuerreiro.getText().toUpperCase());
                g.setArmamento(jtfArmaGuerreiro.getText().toUpperCase());
                if (jrbFemininoGuerreiro.isSelected() || jrbMasculinoGuerreiro.isSelected()) {
                    g.setSexo(!jrbFemininoGuerreiro.isSelected());
                }
                GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
                guerreiroS.cadastrarGuerreiro(g);
                addRowToTable();
                limpaCampos();
            }//fim salvar
        } else {//update
            Guerreiro gue = new Guerreiro();
            gue.setId(idEdit);
            gue.setNome(jtfNomeGuerreiro.getText().toUpperCase());
            gue.setCabelo(jtfCabeloGuerreiro.getText().toUpperCase());
            gue.setOlho(jtfOlhoGuerreiro.getText().toUpperCase());
            gue.setPele(jtfPeleGuerreiro.getText().toUpperCase());
            gue.setArmamento(jtfArmaGuerreiro.getText().toUpperCase());
            GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
            guerreiroS.atualizarGuerreiro(gue);
            addRowToTable();
            limpaCampos();
            JOptionPane.showMessageDialog(this, "Vitima atualizda com sucesso!");
            jbDefault();
        }//fim update
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarGuerreiroActionPerformed

    private void jtfNomeGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeGuerreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeGuerreiroActionPerformed

    private void jtfCabeloGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCabeloGuerreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCabeloGuerreiroActionPerformed

    private void jtfPeleGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPeleGuerreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPeleGuerreiroActionPerformed

    private void jtfOlhoGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOlhoGuerreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOlhoGuerreiroActionPerformed

    private void jrbFemininoGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFemininoGuerreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFemininoGuerreiroActionPerformed

    private void jrbMasculinoGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMasculinoGuerreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMasculinoGuerreiroActionPerformed

    private void jbEditarGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarGuerreiroActionPerformed
        // TODO add your handling code here:
        jbLimparGuerreiro.setEnabled(false);
        jbSalvarGuerreiro.setText("Atualizar");
        jbDeletarGuerreiro.setText("Cancelar");
        jrbFemininoGuerreiro.setVisible(false);
        jrbMasculinoGuerreiro.setVisible(false);
        jLSexoGuerreiro.setVisible(false);

        //buscar vítima e carregar nos campos
        int linha = jtGuerreiro.getSelectedRow();
        idEdit = (int) jtGuerreiro.getValueAt(linha, 0);
        GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
        Guerreiro guerreiro = guerreiroS.getGuerreiroById(idEdit);
        //carrega na tela
        jtfNomeGuerreiro.setText(guerreiro.getNome());
        jtfCabeloGuerreiro.setText(guerreiro.getCabelo());
        jtfOlhoGuerreiro.setText(guerreiro.getOlho());
        jtfPeleGuerreiro.setText(guerreiro.getPele());
        jtfArmaGuerreiro.setText(guerreiro.getArmamento());
    }//GEN-LAST:event_jbEditarGuerreiroActionPerformed

    private void jbDeletarGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarGuerreiroActionPerformed
        // TODO add your handling code here:
        if (jbDeletarGuerreiro.getText().equals("Deletar")) {

            int linha = jtGuerreiro.getSelectedRow();
            int id = (int) jtGuerreiro.getValueAt(linha, 0);
            String nome = (String) jtGuerreiro.getValueAt(linha, 1);
            Object[] btnMSG = {"Sim", "Não"};
            int resp = JOptionPane.showOptionDialog(this, "Deseja deletar " + nome + "?", "--Deletar--", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, btnMSG, btnMSG[0]);
            if (resp == 0) {
                GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
                guerreiroS.deletarGuerreiro(id);
                addRowToTable();
                JOptionPane.showMessageDialog(this, "Vítima " + nome + " deletada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "OK, delete cancelado pelo usuário!");
            }
            jbDeletarGuerreiro.setVisible(false);
            jbEditarGuerreiro.setVisible(false);
        } else {
            limpaCampos();
            jbDefault();
        }
    }//GEN-LAST:event_jbDeletarGuerreiroActionPerformed

    private void jrbFemininoGuerreiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFemininoGuerreiroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFemininoGuerreiroMouseClicked

    private void jtGuerreiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtGuerreiroMouseClicked
        // TODO add your handling code here:
        jbDeletarGuerreiro.setVisible(true);
        jbEditarGuerreiro.setVisible(true);
    }//GEN-LAST:event_jtGuerreiroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGuerreiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGuerreiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGuerreiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGuerreiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGuerreiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexoGuerreiro;
    private javax.swing.JLabel jLSexoGuerreiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneG;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbDeletarGuerreiro;
    private javax.swing.JButton jbEditarGuerreiro;
    private javax.swing.JButton jbLimparGuerreiro;
    private javax.swing.JButton jbSalvarGuerreiro;
    private javax.swing.JRadioButton jrbFemininoGuerreiro;
    private javax.swing.JRadioButton jrbMasculinoGuerreiro;
    private javax.swing.JTable jtGuerreiro;
    private javax.swing.JTextField jtfArmaGuerreiro;
    private javax.swing.JTextField jtfCabeloGuerreiro;
    private javax.swing.JTextField jtfNomeGuerreiro;
    private javax.swing.JTextField jtfOlhoGuerreiro;
    private javax.swing.JTextField jtfPeleGuerreiro;
    // End of variables declaration//GEN-END:variables

    
}
