/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ladrao;
import servicos.LadraoServicos;
import servicos.ServicosFactory;

/**
 *
 * @author 182310086
 */
public class JFLadrao extends javax.swing.JFrame {
    int idEdit;

    /**
     * Creates new form JFLadrao
     */
    public JFLadrao() {
        initComponents();
        addRowToTable();
        jbDeletarLadrao.setVisible(false);
        jbEditarLadrao.setVisible(false);
    }
    
    private void addRowToTable() {
        //pega a modelagem da tabela na inteface grafica
        DefaultTableModel model = (DefaultTableModel) jtLadrao.getModel();
        model.getDataVector().removeAllElements();//remove linhas
        model.fireTableDataChanged();
        Object rowData[] = new Object[6];//vetor da tabela
        LadraoServicos ladraoS = ServicosFactory.getLadraoServicos();
        //ler dados e add no vetor e tabela
        for (Ladrao ladrao : ladraoS.listaLadroes()) {
            rowData[0] = ladrao.getId();
            rowData[1] = ladrao.getNome();            
            rowData[2] = ladrao.getPele();
            rowData[3] = ladrao.isSexo() == false ? "FEMININO" : "MASCULINO";//if ternary
            rowData[4] = ladrao.getPontoDeVida();
            rowData[5] = ladrao.getPlanoDeFuga();
            model.addRow(rowData);
        }

    }//fim add table
    
    private void limpaCampos() {
        jtfNomeLadrao.setText("");
        jtfOlhoLadrao.setText("");
        jtfCabeloLadrao.setText("");
        jtfPeleLadrao.setText("");
        bgSexoLadrao.clearSelection();
        jtfPlanoDeFugaLadrao.setText("");
        jtfNomeLadrao.requestFocus();
    }//limpa campos
    
    private boolean validaInputs() {
        if (jtfNomeLadrao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o nome");
            jtfNomeLadrao.requestFocus();
            return false;
        }
        if (jtfCabeloLadrao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o cabelo");
            jtfCabeloLadrao.requestFocus();
            return false;
        }
        if (jtfOlhoLadrao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o olho");
            jtfOlhoLadrao.requestFocus();
            return false;
        }
        if (jtfPeleLadrao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher a pele");
            jtfPeleLadrao.requestFocus();
            return false;
        }
        if (!jrbFemininoLadrao.isSelected() && !jrbMasculinoLadrao.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecionar sexo!");
            return false;
        }//o sinal de ! está negando o retorno do select
        
        if (jtfPlanoDeFugaLadrao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher Plano de Fuga");
            jtfPlanoDeFugaLadrao.requestFocus();
            return false;            
        }
        return true;
       
    }//validando dados
    
    private void jbDefault() {
        jbSalvarLadrao.setText("Salvar");
        jLSexoLadrao.setVisible(true);
        jrbFemininoLadrao.setVisible(true);
        jrbMasculinoLadrao.setVisible(true);
        jbLimparLadrao.setEnabled(true);
        jbDeletarLadrao.setText("Deletar");
        jbDeletarLadrao.setVisible(false);
        jbEditarLadrao.setVisible(false);
    }//botoes zerados

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexoLadrao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeLadrao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCabeloLadrao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfOlhoLadrao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfPeleLadrao = new javax.swing.JTextField();
        jLSexoLadrao = new javax.swing.JLabel();
        jrbFemininoLadrao = new javax.swing.JRadioButton();
        jrbMasculinoLadrao = new javax.swing.JRadioButton();
        jbSalvarLadrao = new javax.swing.JButton();
        jbLimparLadrao = new javax.swing.JButton();
        jbEditarLadrao = new javax.swing.JButton();
        jbDeletarLadrao = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtfPlanoDeFugaLadrao = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLadrao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Ladrão");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cabelo: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Olho:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Pele: ");

        jLSexoLadrao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLSexoLadrao.setText("Sexo: ");

        bgSexoLadrao.add(jrbFemininoLadrao);
        jrbFemininoLadrao.setText("Feminino");

        bgSexoLadrao.add(jrbMasculinoLadrao);
        jrbMasculinoLadrao.setText("Masculino");

        jbSalvarLadrao.setText("Salvar");
        jbSalvarLadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarLadraoActionPerformed(evt);
            }
        });

        jbLimparLadrao.setText("Limpar");
        jbLimparLadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparLadraoActionPerformed(evt);
            }
        });

        jbEditarLadrao.setText("Editar");
        jbEditarLadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarLadraoActionPerformed(evt);
            }
        });

        jbDeletarLadrao.setText("Deletar");
        jbDeletarLadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarLadraoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Plano de Fuga: ");

        jtLadrao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Pele", "Sexo", "Hp", "Fuga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLadrao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLadraoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLadrao);
        if (jtLadrao.getColumnModel().getColumnCount() > 0) {
            jtLadrao.getColumnModel().getColumn(0).setResizable(false);
            jtLadrao.getColumnModel().getColumn(1).setResizable(false);
            jtLadrao.getColumnModel().getColumn(2).setResizable(false);
            jtLadrao.getColumnModel().getColumn(3).setResizable(false);
            jtLadrao.getColumnModel().getColumn(4).setResizable(false);
            jtLadrao.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNomeLadrao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCabeloLadrao)
                            .addComponent(jtfPeleLadrao, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLSexoLadrao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfOlhoLadrao)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbMasculinoLadrao)
                                    .addComponent(jrbFemininoLadrao))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSalvarLadrao)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimparLadrao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jbEditarLadrao)
                        .addGap(19, 19, 19)
                        .addComponent(jbDeletarLadrao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPlanoDeFugaLadrao)))
                .addContainerGap())
            .addComponent(jSeparator2)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNomeLadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jtfOlhoLadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jrbFemininoLadrao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbMasculinoLadrao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfCabeloLadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfPeleLadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSexoLadrao))))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfPlanoDeFugaLadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarLadrao)
                    .addComponent(jbLimparLadrao)
                    .addComponent(jbEditarLadrao)
                    .addComponent(jbDeletarLadrao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimparLadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparLadraoActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_jbLimparLadraoActionPerformed

    private void jbSalvarLadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarLadraoActionPerformed
        // TODO add your handling code here:
        if (jbSalvarLadrao.getText().equals("Salvar")) {
            if (validaInputs()) {
                Ladrao l = new Ladrao();
                l.setNome(jtfNomeLadrao.getText().toUpperCase());
                l.setOlho(jtfOlhoLadrao.getText().toUpperCase());
                l.setCabelo(jtfCabeloLadrao.getText().toUpperCase());
                l.setPele(jtfPeleLadrao.getText().toUpperCase());                
                if (jrbFemininoLadrao.isSelected() || jrbMasculinoLadrao.isSelected()) {
                    l.setSexo(!jrbFemininoLadrao.isSelected());
                }
                l.setPlanoDeFuga(jtfPlanoDeFugaLadrao.getText().toUpperCase());
                LadraoServicos ladraoS = ServicosFactory.getLadraoServicos();
                ladraoS.cadastrarLadrao(l);
                addRowToTable();
                limpaCampos();
            }//fim salvar
        } else {//update
            Ladrao lad = new Ladrao();
            lad.setId(idEdit);
            lad.setNome(jtfNomeLadrao.getText().toUpperCase());
            lad.setCabelo(jtfCabeloLadrao.getText().toUpperCase());
            lad.setOlho(jtfOlhoLadrao.getText().toUpperCase());
            lad.setPele(jtfPeleLadrao.getText().toUpperCase());
            lad.setPlanoDeFuga(jtfPlanoDeFugaLadrao.getText().toUpperCase());
            LadraoServicos ladraoS = ServicosFactory.getLadraoServicos();
            ladraoS.atualizarLadrao(lad);
            addRowToTable();
            limpaCampos();
            JOptionPane.showMessageDialog(this, "Ladrão atualizdo com sucesso!");
            jbDefault();
        }//fim update
    }//GEN-LAST:event_jbSalvarLadraoActionPerformed

    private void jtLadraoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLadraoMouseClicked
        // TODO add your handling code here:
        jbDeletarLadrao.setVisible(true);
        jbEditarLadrao.setVisible(true);
    }//GEN-LAST:event_jtLadraoMouseClicked

    private void jbDeletarLadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarLadraoActionPerformed
        // TODO add your handling code here:
        if (jbDeletarLadrao.getText().equals("Deletar")) {

            int linha = jtLadrao.getSelectedRow();
            int id = (int) jtLadrao.getValueAt(linha, 0);
            String nome = (String) jtLadrao.getValueAt(linha, 1);
            Object[] btnMSG = {"Sim", "Não"};
            int resp = JOptionPane.showOptionDialog(this, "Deseja deletar " + nome + "?", "--Deletar--", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, btnMSG, btnMSG[0]);
            if (resp == 0) {
                LadraoServicos ladraoS = ServicosFactory.getLadraoServicos();
                ladraoS.deletarLadrao(id);
                addRowToTable();
                JOptionPane.showMessageDialog(this, "Ladrão " + nome + " deletado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "OK, delete cancelado pelo usuário!");
            }
            jbDeletarLadrao.setVisible(false);
            jbEditarLadrao.setVisible(false);
        } else {
            limpaCampos();
            jbDefault();
        }
    }//GEN-LAST:event_jbDeletarLadraoActionPerformed

    private void jbEditarLadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarLadraoActionPerformed
        // TODO add your handling code here:
        jbLimparLadrao.setEnabled(false);
        jbSalvarLadrao.setText("Atualizar");
        jbDeletarLadrao.setText("Cancelar");
        jrbFemininoLadrao.setVisible(false);
        jrbMasculinoLadrao.setVisible(false);
        jLSexoLadrao.setVisible(false);
        

        //buscar vítima e carregar nos campos
        int linha = jtLadrao.getSelectedRow();
        idEdit = (int) jtLadrao.getValueAt(linha, 0);
        LadraoServicos ladraoS = ServicosFactory.getLadraoServicos();
        Ladrao ladrao = ladraoS.getLadraoById(idEdit);
        //carrega na tela
        jtfNomeLadrao.setText(ladrao.getNome());
        jtfCabeloLadrao.setText(ladrao.getCabelo());
        jtfOlhoLadrao.setText(ladrao.getOlho());
        jtfPeleLadrao.setText(ladrao.getPele());
        jtfPlanoDeFugaLadrao.setText(ladrao.getPlanoDeFuga());
    }//GEN-LAST:event_jbEditarLadraoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexoLadrao;
    private javax.swing.JLabel jLSexoLadrao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbDeletarLadrao;
    private javax.swing.JButton jbEditarLadrao;
    private javax.swing.JButton jbLimparLadrao;
    private javax.swing.JButton jbSalvarLadrao;
    private javax.swing.JRadioButton jrbFemininoLadrao;
    private javax.swing.JRadioButton jrbMasculinoLadrao;
    private javax.swing.JTable jtLadrao;
    private javax.swing.JTextField jtfCabeloLadrao;
    private javax.swing.JTextField jtfNomeLadrao;
    private javax.swing.JTextField jtfOlhoLadrao;
    private javax.swing.JTextField jtfPeleLadrao;
    private javax.swing.JTextField jtfPlanoDeFugaLadrao;
    // End of variables declaration//GEN-END:variables
}
