/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pessoa;
import servicos.ServicosFactory;
import servicos.VitimaServicos;

/**
 *
 * @author 182310086
 */
public class JFVitima extends javax.swing.JFrame {

    int idEdit;

    /**
     * Creates new form JFVitima
     */
    public JFVitima() {
        initComponents();
        addRowToTable();
        jbDeletarVitima.setVisible(false);
        jbEditarVitima.setVisible(false);
    }

    private void addRowToTable() {
        //pega a modelagem da tabela na inteface grafica
        DefaultTableModel model = (DefaultTableModel) jtVitimas.getModel();
        model.getDataVector().removeAllElements();//remove linhas
        model.fireTableDataChanged();
        Object rowData[] = new Object[6];//vetor da tabela
        VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
        //ler dados e add no vetor e tabela
        for (Pessoa vitima : vitimaS.listaVitimas()) {
            rowData[0] = vitima.getId();
            rowData[1] = vitima.getNome();
            rowData[2] = vitima.getOlho();
            rowData[3] = vitima.getPele();
            rowData[4] = vitima.isSexo() == false ? "FEMININO" : "MASCULINO";//if ternary
            rowData[5] = vitima.getPontoDeVida();
            model.addRow(rowData);
        }

    }//fim add table

    private void limpaCampos() {
        jtfNomeVitima.setText("");
        jtfOlhoVitima.setText("");
        jtfCabeloVitima.setText("");
        jtfPeleVitima.setText("");
        bgSexoVitima.clearSelection();
        jtfNomeVitima.requestFocus();
    }//limpa campos

    private boolean validaInputs() {
        if (jtfNomeVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o nome");
            jtfNomeVitima.requestFocus();
            return false;
        }
        if (jtfCabeloVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o cabelo");
            jtfCabeloVitima.requestFocus();
            return false;
        }
        if (jtfOlhoVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher o olho");
            jtfOlhoVitima.requestFocus();
            return false;
        }
        if (jtfPeleVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preeencher a pele");
            jtfPeleVitima.requestFocus();
            return false;
        }
        if (!jrbFemininoVitima.isSelected() && !jrbMasculinoVitima.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecionar sexo!");
            return false;
        }//o sinal de ! está negando o retorno do select
        return true;
    }//validando dados

    private void jbDefault() {
        jbSalvarVitima.setText("Salvar");
        jLSexoVitima.setVisible(true);
        jrbFemininoVitima.setVisible(true);
        jrbMasculinoVitima.setVisible(true);
        jbLimparVitima.setEnabled(true);
        jbDeletarVitima.setText("Deletar");
        jbDeletarVitima.setVisible(false);
        jbEditarVitima.setVisible(false);
    }//botoes zerados

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexoVitima = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeVitima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCabeloVitima = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfOlhoVitima = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfPeleVitima = new javax.swing.JTextField();
        jLSexoVitima = new javax.swing.JLabel();
        jrbFemininoVitima = new javax.swing.JRadioButton();
        jrbMasculinoVitima = new javax.swing.JRadioButton();
        jbSalvarVitima = new javax.swing.JButton();
        jbLimparVitima = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVitimas = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jbDeletarVitima = new javax.swing.JButton();
        jbEditarVitima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Vítima");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jtfNomeVitima.setToolTipText("");
        jtfNomeVitima.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cabelo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Olho:");

        jtfOlhoVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOlhoVitimaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Pele: ");

        jLSexoVitima.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLSexoVitima.setText("Sexo:");

        bgSexoVitima.add(jrbFemininoVitima);
        jrbFemininoVitima.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbFemininoVitima.setText("Feminino");
        jrbFemininoVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFemininoVitimaActionPerformed(evt);
            }
        });

        bgSexoVitima.add(jrbMasculinoVitima);
        jrbMasculinoVitima.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbMasculinoVitima.setText("Masculino");
        jrbMasculinoVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMasculinoVitimaActionPerformed(evt);
            }
        });

        jbSalvarVitima.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSalvarVitima.setText("Salvar");
        jbSalvarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarVitimaActionPerformed(evt);
            }
        });

        jbLimparVitima.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbLimparVitima.setText("Limpar");
        jbLimparVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparVitimaActionPerformed(evt);
            }
        });

        jtVitimas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Olho", "Pele", "Sexo", "Vida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVitimas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVitimasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtVitimas);
        if (jtVitimas.getColumnModel().getColumnCount() > 0) {
            jtVitimas.getColumnModel().getColumn(0).setResizable(false);
            jtVitimas.getColumnModel().getColumn(1).setResizable(false);
            jtVitimas.getColumnModel().getColumn(2).setResizable(false);
            jtVitimas.getColumnModel().getColumn(3).setResizable(false);
            jtVitimas.getColumnModel().getColumn(4).setResizable(false);
            jtVitimas.getColumnModel().getColumn(5).setResizable(false);
        }

        jbDeletarVitima.setText("Deletar");
        jbDeletarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarVitimaActionPerformed(evt);
            }
        });

        jbEditarVitima.setText("Editar");
        jbEditarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarVitimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jtfNomeVitima))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfPeleVitima, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCabeloVitima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLSexoVitima)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbMasculinoVitima)
                            .addComponent(jrbFemininoVitima)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfOlhoVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSalvarVitima)
                .addGap(18, 18, 18)
                .addComponent(jbLimparVitima)
                .addGap(18, 18, 18)
                .addComponent(jbEditarVitima)
                .addGap(18, 18, 18)
                .addComponent(jbDeletarVitima)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNomeVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCabeloVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfOlhoVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbFemininoVitima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbMasculinoVitima))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfPeleVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSexoVitima))))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarVitima)
                    .addComponent(jbLimparVitima)
                    .addComponent(jbEditarVitima)
                    .addComponent(jbDeletarVitima))
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfOlhoVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOlhoVitimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOlhoVitimaActionPerformed

    private void jrbMasculinoVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMasculinoVitimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMasculinoVitimaActionPerformed

    private void jbLimparVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparVitimaActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jbLimparVitimaActionPerformed

    private void jbSalvarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarVitimaActionPerformed
        if (jbSalvarVitima.getText().equals("Salvar")) {
            if (validaInputs()) {
                Pessoa v = new Pessoa();
                v.setNome(jtfNomeVitima.getText().toUpperCase());
                v.setOlho(jtfOlhoVitima.getText().toUpperCase());
                v.setCabelo(jtfCabeloVitima.getText().toUpperCase());
                v.setPele(jtfPeleVitima.getText().toUpperCase());
                if (jrbFemininoVitima.isSelected() || jrbMasculinoVitima.isSelected()) {
                    v.setSexo(!jrbFemininoVitima.isSelected());
                }
                VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
                vitimaS.cadastrarVitima(v);
                addRowToTable();
                limpaCampos();
            }//fim salvar
        } else {//update
            Pessoa vit = new Pessoa();
            vit.setId(idEdit);
            vit.setNome(jtfNomeVitima.getText().toUpperCase());
            vit.setCabelo(jtfCabeloVitima.getText().toUpperCase());
            vit.setOlho(jtfOlhoVitima.getText().toUpperCase());
            vit.setPele(jtfPeleVitima.getText().toUpperCase());
            VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
            vitimaS.atualizarVitima(vit);
            addRowToTable();
            limpaCampos();
            JOptionPane.showMessageDialog(this, "Vitima atualizda com sucesso!");
            jbDefault();
        }//fim update
    }//GEN-LAST:event_jbSalvarVitimaActionPerformed

    private void jrbFemininoVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFemininoVitimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFemininoVitimaActionPerformed

    private void jtVitimasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVitimasMouseClicked
        // TODO add your handling code here:
        jbDeletarVitima.setVisible(true);
        jbEditarVitima.setVisible(true);
    }//GEN-LAST:event_jtVitimasMouseClicked

    private void jbDeletarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarVitimaActionPerformed
        // TODO add your handling code here:
        if (jbDeletarVitima.getText().equals("Deletar")) {

            int linha = jtVitimas.getSelectedRow();
            int id = (int) jtVitimas.getValueAt(linha, 0);
            String nome = (String) jtVitimas.getValueAt(linha, 1);
            Object[] btnMSG = {"Sim", "Não"};
            int resp = JOptionPane.showOptionDialog(this, "Deseja deletar " + nome + "?", "--Deletar--", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, btnMSG, btnMSG[0]);
            if (resp == 0) {
                VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
                vitimaS.deletarVitima(id);
                addRowToTable();
                JOptionPane.showMessageDialog(this, "Vítima " + nome + " deletada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "OK, delete cancelado pelo usuário!");
            }
            jbDeletarVitima.setVisible(false);
            jbEditarVitima.setVisible(false);
        } else {
            limpaCampos();
            jbDefault();
        }
    }//GEN-LAST:event_jbDeletarVitimaActionPerformed

    private void jbEditarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarVitimaActionPerformed
        jbLimparVitima.setEnabled(false);
        jbSalvarVitima.setText("Atualizar");
        jbDeletarVitima.setText("Cancelar");
        jrbFemininoVitima.setVisible(false);
        jrbMasculinoVitima.setVisible(false);
        jLSexoVitima.setVisible(false);

        //buscar vítima e carregar nos campos
        int linha = jtVitimas.getSelectedRow();
        idEdit = (int) jtVitimas.getValueAt(linha, 0);
        VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
        Pessoa vitima = vitimaS.getVitimaById(idEdit);
        //carrega na tela
        jtfNomeVitima.setText(vitima.getNome());
        jtfCabeloVitima.setText(vitima.getCabelo());
        jtfOlhoVitima.setText(vitima.getOlho());
        jtfPeleVitima.setText(vitima.getPele());


    }//GEN-LAST:event_jbEditarVitimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVitima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexoVitima;
    private javax.swing.JLabel jLSexoVitima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbDeletarVitima;
    private javax.swing.JButton jbEditarVitima;
    private javax.swing.JButton jbLimparVitima;
    private javax.swing.JButton jbSalvarVitima;
    private javax.swing.JRadioButton jrbFemininoVitima;
    private javax.swing.JRadioButton jrbMasculinoVitima;
    private javax.swing.JTable jtVitimas;
    private javax.swing.JTextField jtfCabeloVitima;
    private javax.swing.JTextField jtfNomeVitima;
    private javax.swing.JTextField jtfOlhoVitima;
    private javax.swing.JTextField jtfPeleVitima;
    // End of variables declaration//GEN-END:variables
}
